[project]
name = "telerun"
version = "1.0.0"
description = "A wrapper to run telerun"
requires-python = ">=3.11"

[project.scripts]
telerun = "telerun.submit:main"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"